name: Nuget Release

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-5.0
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install xml2js
      - run: npm install child_process      
      - name: Release Nuget
        uses: nexmo/github-actions/nuget-release@nuget-release
        env:
          PROJECT_FILE : NugetActionTest.csproj
          VERSION : ${{ github.event.release.tag_name }}
          BRANCH: main
          ORGANIZATION: slorello89
          REPO: test-nuget-action
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
